services:
  velodyne:
    image: husarion/velodyne:noetic
    container_name: velodyne
    network_mode: host
    command: >
      roslaunch velodyne_pointcloud VLP16_points.launch
        device_ip:=10.15.20.10
        frame_id:=velodyne
        port:=2368
