x-common-config: &common-config
  network_mode: host
  ipc: host
  restart: always
  environment:
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp # Default FastDDS do not work
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}

services:
  velodyne:
    image: husarion/velodyne:humble-2.4.0-20240722
    container_name: velodyne
    <<: *common-config
    volumes:
      - ./config/panther_velodyne_pointcloud.yaml:/config/panther_velodyne_pointcloud.yaml
      - ./config/panther_velodyne_driver.yaml:/config/panther_velodyne_driver.yaml
      - ./velodyne.launch.py:/velodyne.launch.py
    command: >
      ros2 launch /velodyne.launch.py
        transform_params_file:=/config/panther_velodyne_pointcloud.yaml
        driver_params_file:=/config/panther_velodyne_driver.yaml
        robot_namespace:=panther/
